### PR TITLE
Fix the redirect loop test.

### PR DESCRIPTION
**Pull request by giancarlosotelo**
Fix for the redirect loop test to work.

### CODE REVIEW

**Comment by dawehner** [comment]
so I think this won't fly in  case you don't have rewrite enabled because then baseUrl() would not contain index.php, but why can't you do that PathSubscriber is doing: rtrim($request->getPathInfo());

**Comment by Berdir** [comment]
Oh, we are using that, see https://github.com/md-systems/redirect/blob/8.x-1.x/src/EventSubscriber/RedirectRequestSubscriber.php#L89

But this is _not_ the path coming from the request, that's the problem.

We first load a redirect for the incoming path and if we have a match (lets say, /whatever redirects to /node), we want to make sure that /node doesn't redirect back to /whatever (or to /bla, which then redirects to /whatever).

So yes, we need *exactly what getPathInfo() gives us. Based on a Url object.

**Comment by dawehner** [comment]
Given that

 $base_url = $this->context->getBaseUrl()
 $url = $base_url . $path . $fragment;

the proposed patch seems fine

**Comment by Berdir** [comment]
Ok, merging for now. I'm not sure this really works for e.g. language prefixes, but we can try to write a failing test ;)

**Pull request merged**
